services:
  servicoBanco:  # Nome do serviço
    image: mysql:latest  # Imagem do Docker a ser utilizada
    container_name: containerMysql  # Nome do container
    restart: always  # Reinicia o container automaticamente se ele parar
    environment:
      MYSQL_DATABASE: financeiro  # Nome do banco de dados
      MYSQL_ROOT_PASSWORD: 12345  # Senha do usuário root
      MYSQL_USER: userDB  # Nome do usuário
      MYSQL_PASSWORD: 12345  # Senha do usuário
    ports:
      - "3306:3306"  # Mapeia a porta local 3306 para a porta 3306 do container
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  db_data: