spring:
  application:
    name: financeiro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${URL_BANCO}:3306/financeiro
    username: userDB
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET}


springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

cambio:
  url: http://api.exchangeratesapi.io/v1/latest?
  chave: ${CHAVE_API}
  simbolos: BRL,USD,JPY,ARS

mock:
  cambio:
    url: https://${MOCK_API}.mockapi.io/api/v1/valores/1
