spring:
  application:
    name: financeiro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financeiro
    username: userDB
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:1111111}


springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

cambio:
  url: http://api.exchangeratesapi.io/v1/latest?
  chave: ${CHAVE_API}
  simbolos: BRL,USD,JPY,ARS
